BEGIN;

DROP TABLE IF EXISTS "artist_details" CASCADE;
DROP TABLE IF EXISTS "artist_headers" CASCADE;
DROP TABLE IF EXISTS "artist_gallery" CASCADE;
DROP TABLE IF EXISTS "artist_posters" CASCADE;
DROP TABLE IF EXISTS "artist_external_links" CASCADE;
DROP TABLE IF EXISTS "artist_associations" CASCADE;
DROP TABLE IF EXISTS "stores" CASCADE;
DROP TABLE IF EXISTS "releases" CASCADE;
DROP TABLE IF EXISTS "subscriptions" CASCADE;
DROP TABLE IF EXISTS "artists" CASCADE;
DROP TABLE IF EXISTS "last_actions" CASCADE;

COMMIT;