#!/usr/bin/env bash

if ! which gometalinter > /dev/null; then
    echo "==> Installing gometalinter..."
    go get -u github.com/alecthomas/gometalinter
    gometalinter --debug --install
fi

echo "==> Checking deadcode..."
gometalinter --disable-all --enable deadcode ./internal/...
echo "==> Checking gochecknoinits..."
gometalinter --disable-all --enable gochecknoinits ./internal/...
echo "==> Checking goconst..."
gometalinter --disable-all --enable goconst ./internal/...
echo "==> Checking gocyclo..."
gometalinter --disable-all --enable gocyclo ./internal/...
echo "==> Checking goimports..."
gometalinter --disable-all --enable goimports ./internal/...
echo "==> Checking golint..."
gometalinter --disable-all --enable golint ./internal/... --exclude 'should have comment'
echo "==> Checking gosimple..."
gometalinter --disable-all --enable gosimple ./internal/... --exclude 'should use for range'
echo "==> Checking gotypex..."
gometalinter --disable-all --enable gotypex ./internal/...
echo "==> Checking ineffassign..."
gometalinter --disable-all --enable ineffassign ./internal/...
echo "==> Checking interfacer..."
gometalinter --disable-all --enable interfacer ./internal/...
echo "==> Checking maligned..."
gometalinter --disable-all --enable maligned ./internal/...
echo "==> Checking misspell..."
gometalinter --disable-all --enable misspell ./internal/...
echo "==> Checking nakedret..."
gometalinter --disable-all --enable nakedret ./internal/...
echo "==> Checking safesql..."
gometalinter --disable-all --enable safesql ./internal/...
echo "==> Checking staticcheck..."
gometalinter --disable-all --enable staticcheck ./internal/...
echo "==> Checking structcheck..."
gometalinter --disable-all --enable structcheck ./internal/...
echo "==> Checking unconvert..."
gometalinter --disable-all --enable unconvert ./internal/...
echo "==> Checking unparam..."
gometalinter --disable-all --enable unparam ./internal/... --exclude 'parameter skip always receives 3'
echo "==> Checking unused..."
gometalinter --disable-all --enable unused ./internal/...
echo "==> Checking varcheck..."
gometalinter --disable-all --enable varcheck ./internal/...
echo "==> Checking gofmt..."
gometalinter --disable-all --enable gofmt ./internal/...

# ignore not critical errors until they will be fixed, but print information
echo "==> Checking dupl..."
gometalinter --disable-all --enable dupl ./internal/... || true
